name: badgr
description: The merit badge tracker for Scouts
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.1
  cloud_firestore: ^4.8.3
  modal_progress_hud_nsn: ^0.4.0
  transitioned_indexed_stack: ^1.0.2
  accordion: ^2.5.1
  flutter_svg: ^2.0.7
  adaptive_theme: ^3.3.0
  percent_indicator: ^4.2.3
  adaptive_dialog: ^1.9.0+2
  async_builder: ^1.3.1+1
  flutter_bloc: ^8.1.3
  dynamic_color: ^1.6.7
  rounded_background_text: ^0.4.3
  firebase_performance: ^0.9.2+6
  keyboard_actions: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - images/badges/
    - images/
    - assets/badgeReqs.json
