// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCd9UUNyr1Fs8bt3cBJrDKCvNxoBagyJ9A',
    appId: '1:469697089497:web:bfcb692b6a58e42aabd3c8',
    messagingSenderId: '469697089497',
    projectId: 'badgr-88835',
    authDomain: 'badgr-88835.firebaseapp.com',
    storageBucket: 'badgr-88835.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu_NgIZoeaA4YH7MbVowZOiBeD3NGteLQ',
    appId: '1:469697089497:android:9cc0106ea55a394fabd3c8',
    messagingSenderId: '469697089497',
    projectId: 'badgr-88835',
    storageBucket: 'badgr-88835.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEMI10ml04zJYp15sui08bY7_cgvoyIks',
    appId: '1:469697089497:ios:c614ba8041a51a65abd3c8',
    messagingSenderId: '469697089497',
    projectId: 'badgr-88835',
    storageBucket: 'badgr-88835.appspot.com',
    iosClientId: '469697089497-i9r77c45n0ifuce2p8bp10h9oj3up5rq.apps.googleusercontent.com',
    iosBundleId: 'com.b1sth3be5t.badgr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEMI10ml04zJYp15sui08bY7_cgvoyIks',
    appId: '1:469697089497:ios:fdf42258184f0de3abd3c8',
    messagingSenderId: '469697089497',
    projectId: 'badgr-88835',
    storageBucket: 'badgr-88835.appspot.com',
    iosClientId: '469697089497-dk98v91406e0m6hulsnmou0a3o32q09h.apps.googleusercontent.com',
    iosBundleId: 'com.b1sth3be5t.badgr.RunnerTests',
  );
}
